### ISSUE TITLE
Pulling from library/mysql no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by edchelstephens** [geekcap-pluralsight/python-docker#2]
Hi Steven, @geekcap-pluralsight 

I have this issue:
`Pulling from library/mysql no matching manifest for linux/arm64/v8 in the manifest list entries`

Is there an alternative to mysql for the db service in this tutorial?
Or do you any alternative mysql image that has arm64 support that I can use to continue the tutorial?

Thanks!

# Software versions:
Docker Compose version v2.5.1
Docker version 20.10.14, build a224086
M1 Pro on macOS Monterey version 12.4

# Steps taken
1. Ran command `docker pull mysql`
2. Got error:
```
docker pull mysql
Using default tag: latest
latest: Pulling from library/mysql
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by edchelstephens** [comment]
Hi @geekcap-pluralsight, Steve,

How can I use `mariadb` or `postgresql` instead of sql in here?

This is actually an known issue for Mac m1:

https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

### "Not all images are available for ARM64 architecture. You can add --platform linux/amd64 to run an Intel image under emulation. In particular, the [mysql](https://hub.docker.com/_/mysql?tab=tags&page=1&ordering=last_updated) image is not available for ARM64. You can work around this issue by using a [mariadb](https://hub.docker.com/_/mariadb?tab=tags&page=1&ordering=last_updated) image."

**Comment by geekcap-pluralsight** [comment]
I faced this on my m1 mac when I was setting up the app to run in Kubernetes and used this image:

K8s config:
- image: arm64v8/mysql:oracle

Docker:
docker pull arm64v8/mysql:oracle

Link:
https://hub.docker.com/r/arm64v8/mysql

I have not tried it directly with Docker, but since it worked for k8s, the Docker image should work. Give it a try and let me know, if it doesn't work I can investigate further.

Thanks,
Steve

**Comment by edchelstephens** [comment]
> I faced this on my m1 mac when I was setting up the app to run in Kubernetes and used this image:
> 
> K8s config:
> 
> * image: arm64v8/mysql:oracle
> 
> Docker: docker pull arm64v8/mysql:oracle
> 
> Link: https://hub.docker.com/r/arm64v8/mysql
> 
> I have not tried it directly with Docker, but since it worked for k8s, the Docker image should work. Give it a try and let me know, if it doesn't work I can investigate further.
> 
> Thanks, Steve

Hi @geekcap-pluralsight Steve, 

Thanks for the reply, 
The image seems to be working.

But I get this new error:

`OperationalError
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'root' (-2)")`

How do I resolve this?

# db container log
```
docker-compose logs db
Attaching to wired-brain_db_1
db_1            | 2022-06-16 22:56:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Initializing database files
db_1            | 2022-06-16T22:56:38.100807Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
db_1            | 2022-06-16T22:56:38.100814Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.29) initializing of server in progress as process 43
db_1            | 2022-06-16T22:56:38.105728Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1            | 2022-06-16T22:56:38.393332Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1            | 2022-06-16T22:56:39.197412Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Database files initialized
db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Starting temporary server
db_1            | 2022-06-16T22:56:41.691799Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
db_1            | 2022-06-16T22:56:41.691810Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 92
db_1            | 2022-06-16T22:56:41.702866Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1            | 2022-06-16T22:56:41.814276Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1            | 2022-06-16T22:56:41.940049Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1            | 2022-06-16T22:56:41.940085Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1            | 2022-06-16T22:56:41.956076Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
db_1            | 2022-06-16T22:56:41.956145Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Temporary server started.
db_1            | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db_1            | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1            |
db_1            | 2022-06-16 22:56:43+00:00 [Note] [Entrypoint]: Stopping temporary server
db_1            | 2022-06-16T22:56:43.934278Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.29).
db_1            | 2022-06-16T22:56:45.565677Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
db_1            | 2022-06-16 22:56:45+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1            |
db_1            | 2022-06-16 22:56:45+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1            |
db_1            | 2022-06-16T22:56:46.112437Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
db_1            | 2022-06-16T22:56:46.112445Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
db_1            | 2022-06-16T22:56:46.116052Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1            | 2022-06-16T22:56:46.185792Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1            | 2022-06-16T22:56:46.273146Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1            | 2022-06-16T22:56:46.273171Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1            | 2022-06-16T22:56:46.290218Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_1            | 2022-06-16T22:56:46.290234Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
db_1            | 2022-06-16T22:57:19.200648Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.29).
db_1            | 2022-06-16T22:57:19.795922Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
```
# Links:

## docker-compose file:
https://github.com/edchelstephens/python-docker-flask/blob/development/wired-brain/docker-compose.yml

## wired-brain project
https://github.com/edchelstephens/python-docker-flask/tree/development/wired-brain

**Comment by edchelstephens** [comment]
> > I faced this on my m1 mac when I was setting up the app to run in Kubernetes and used this image:
> > K8s config:
> > 
> > * image: arm64v8/mysql:oracle
> > 
> > Docker: docker pull arm64v8/mysql:oracle
> > Link: https://hub.docker.com/r/arm64v8/mysql
> > I have not tried it directly with Docker, but since it worked for k8s, the Docker image should work. Give it a try and let me know, if it doesn't work I can investigate further.
> > Thanks, Steve
> 
> Hi @geekcap-pluralsight Steve,
> 
> Thanks for the reply, The image seems to be working.
> 
> But I get this new error:
> 
> `OperationalError sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2005, "Unknown MySQL server host 'root' (-2)")`
> 
> How do I resolve this?
> 
> # db container log
> ```
> docker-compose logs db
> Attaching to wired-brain_db_1
> db_1            | 2022-06-16 22:56:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
> db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
> db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.29-1.el8 started.
> db_1            | 2022-06-16 22:56:38+00:00 [Note] [Entrypoint]: Initializing database files
> db_1            | 2022-06-16T22:56:38.100807Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
> db_1            | 2022-06-16T22:56:38.100814Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.29) initializing of server in progress as process 43
> db_1            | 2022-06-16T22:56:38.105728Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> db_1            | 2022-06-16T22:56:38.393332Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> db_1            | 2022-06-16T22:56:39.197412Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
> db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Database files initialized
> db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Starting temporary server
> db_1            | 2022-06-16T22:56:41.691799Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
> db_1            | 2022-06-16T22:56:41.691810Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 92
> db_1            | 2022-06-16T22:56:41.702866Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> db_1            | 2022-06-16T22:56:41.814276Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> db_1            | 2022-06-16T22:56:41.940049Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
> db_1            | 2022-06-16T22:56:41.940085Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
> db_1            | 2022-06-16T22:56:41.956076Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
> db_1            | 2022-06-16T22:56:41.956145Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
> db_1            | 2022-06-16 22:56:41+00:00 [Note] [Entrypoint]: Temporary server started.
> db_1            | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
> db_1            | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
> db_1            | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
> db_1            | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
> db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
> db_1            | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
> db_1            |
> db_1            | 2022-06-16 22:56:43+00:00 [Note] [Entrypoint]: Stopping temporary server
> db_1            | 2022-06-16T22:56:43.934278Z 11 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.29).
> db_1            | 2022-06-16T22:56:45.565677Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
> db_1            | 2022-06-16 22:56:45+00:00 [Note] [Entrypoint]: Temporary server stopped
> db_1            |
> db_1            | 2022-06-16 22:56:45+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
> db_1            |
> db_1            | 2022-06-16T22:56:46.112437Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
> db_1            | 2022-06-16T22:56:46.112445Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
> db_1            | 2022-06-16T22:56:46.116052Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
> db_1            | 2022-06-16T22:56:46.185792Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
> db_1            | 2022-06-16T22:56:46.273146Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
> db_1            | 2022-06-16T22:56:46.273171Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
> db_1            | 2022-06-16T22:56:46.290218Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
> db_1            | 2022-06-16T22:56:46.290234Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
> db_1            | 2022-06-16T22:57:19.200648Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.29).
> db_1            | 2022-06-16T22:57:19.795922Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
> ```
> 
> # Links:
> ## docker-compose file:
> https://github.com/edchelstephens/python-docker-flask/blob/development/wired-brain/docker-compose.yml
> 
> ## wired-brain project
> https://github.com/edchelstephens/python-docker-flask/tree/development/wired-brain

Hi Steve @geekcap-pluralsight ,

It was a typo on my end on the 
The URI should be 
# mysql://root:password@db/products 
not 
## mysql://root/password@db/products

This fixed it:

## `app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:password@db/products"`

Thank you so much Steve for the help.
I really appreciate it!

Cheers,
Ed
